print("ingrese su nombre: ")
nombre = input()
print ("ingrese su edad: ")
edad= int(input())
print("ingrese su estatura: ")
estatura= float(input())
print ("su nombre es:", nombre)
print ("su edad es:", edad)
print ("su estatura es:", estatura)