nombre = str(input("ingrese su nombre: "))
edad= str(input("ingrese su edad: "))
estatura= float(input("ingrese su estatura: "))
print ("su nombre es:", nombre)
print ("su edad es:", edad)
print ("su estatura es:", estatura)